name: Update Prices Daily

on:
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight UTC
  workflow_dispatch: # Allows manual run

# Add permissions to allow write access
permissions:
  contents: write

jobs:
  update-prices:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install
      env:
        PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: 'true'

    - name: Fetch prices
      run: node fetch_continente_prices.js
      env:
        PUPPETEER_EXECUTABLE_PATH: "/usr/bin/google-chrome"

    - name: Commit and push changes
      run: |
        git config --local user.name "GitHub Action"
        git config --local user.email "action@github.com"
        git add .
        git commit -m "Daily price update $(date +'%Y-%m-%d')" || echo "No changes to commit"
        git push

    # Optional: List files after script execution
    - name: List files after script execution
      run: ls -al

    # Optional: Print environment variables
    - name: Print environment variables
      run: printenv

    - name: Clean up and complete
      run: echo "Price history update completed!"
