name: Update Prices Daily

on:
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight UTC
  workflow_dispatch: # Allows manual run

jobs:
  update-prices:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16' # or your preferred Node.js version

      - name: Install dependencies
        run: npm install

      - name: Run the price fetch script
        run: node fetch_continente_prices.js

      # Debugging step: Check if any files have been modified
      - name: Check Git status before adding files
        run: git status

      - name: Commit and push changes
        run: |
          git config --local user.name "GitHub Action"
          git config --local user.email "action@github.com"
          git add .

          # Debugging step: Check Git status again after adding files
          git status

          # Check if there are changes to commit
          if ! git diff-index --quiet HEAD; then
            git commit -m "Daily price update $(date +'%Y-%m-%d')"
            git push
          else
            echo "No changes to commit"
          fi
        shell: bash

      # Debugging step: List files after script execution
      - name: List files after script execution
        run: ls -al

      # Debugging step: Print environment variables
      - name: Print environment variables
        run: printenv

      - name: Clean up and complete
        run: echo "Price history update completed!"
